tryci: update ci

diff --git a/.github/workflows/nix-test.yaml b/.github/workflows/nix-test.yaml
--- a/.github/workflows/nix-test.yaml
+++ b/.github/workflows/nix-test.yaml
@@ -7,12 +7,22 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+        uses: actions/checkout@v4
 
       - name: Install Nix
         uses: cachix/install-nix-action@v20
 
       - name: Nix Test
-        run: nix eval .#evalTests --show-trace --print-build-logs --verbose
+        run: |
+          if nix eval .#evalTests --show-trace --print-build-logs --verbose; then
+            echo "success=true" >> $GITHUB_ENV
+          else
+            echo "Eval test failed, listing flake.lock for debugging:"
+            cat flake.lock
+            echo "success=false" >> $GITHUB_ENV
+            exit 1
+          fi
+
+      - name: Determine lint result
+        id: build-result
+        run: echo "success=${{ env.success }}" >> $GITHUB_OUTPUT
